### ISSUE TITLE
Final Project 4 - #Ship it - 

### ISSUE THREAD

**Issue by mdewey** [vzmon1/Assignments#43]
With all the work you have been putting into the last 12 weeks, it has all come down to this. Complete your capstone and show it to the world

## Explorer Mode

- [ ] Submit your repository for the capstone project
- [ ] Submit your Url(s) for your capstone project.

**Comment by vzmon1** [comment]
http://nyctours.surge.sh/#/
https://github.com/vzmon1/nyc

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media0.giphy.com/media/4T5sZZstr0oZflIhji/200w_d.gif)
